INSERT INTO TYPEDEF (NAME) VALUES ('INTEGER');
INSERT INTO TYPEDEF (NAME) VALUES ('VARCHAR');
INSERT INTO TYPEDEF (NAME) VALUES ('FK');

INSERT INTO TABLEDEF (NAME) VALUES ('SAMPLE');

INSERT INTO COLUMNDEF (NAME, TABLEID, TYPEID) VALUES ('C1', 1, 1);
INSERT INTO COLUMNDEF (NAME, TABLEID, TYPEID) VALUES ('C2', 1, 1);
INSERT INTO COLUMNDEF (NAME, TABLEID, TYPEID) VALUES ('C3', 1, 1);
INSERT INTO COLUMNDEF (NAME, TABLEID, TYPEID) VALUES ('C4', 1, 1);

INSERT INTO SAMPLE (C1,C2,C3,C4) VALUES (1,3,4,5);
INSERT INTO SAMPLE (C1,C2,C3,C4) VALUES (2,3,4,5);
INSERT INTO SAMPLE (C1,C2,C3,C4) VALUES (3,3,4,5);
INSERT INTO SAMPLE (C1,C2,C3,C4) VALUES (4,3,4,5);
INSERT INTO SAMPLE (C1,C2,C3,C4) VALUES (5,3,4,5);